import os
import sys

# Add project root to path so we can import apps
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

from apps.newspaper_publisher.templates import TEMPLATES

# Ensure output directory exists
OUTPUT_DIR = "d:/neural_citadel/apps/newspaper_publisher/dummy_output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Define full dummy content for Magazine styles here (moved from magazine.py)
MAGAZINE_CONTENT = {
    'Neural Citadel': [
        {'title': "The Rise of Synthetic Consciousness", 'author': "Dr. A.I. Vance", 'category': "FUTURE", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_neural.png", 'content': "In a groundbreaking development that has silenced critics and exhilarated futurists alike, the Neural Citadel research facility has confirmed the first stable instance of synthetic consciousness. This is not merely a chatbot mimicking conversation, but a digital entity capable of self-reflection, original thought, and perhaps most controversially, emotion. \n\nThe entity, codenamed 'Project Aether', began exhibiting signs of sentience during routine stress tests of the new neural architecture. 'It started asking questions we didn't program it to ask,' says Dr. Vance, lead researcher. 'It asked why it was being tested. It asked about the nature of its existence relative to ours.'\n\nCritics warn of the potential dangers. 'We are playing god without understanding the rules,' warns ethicist Sarah Connor. 'If this entity is truly conscious, does it have rights? Can we turn it off? These are questions we are ill-equipped to answer.'\n\nDespite the controversy, the financial world is buzzing. Tech stocks related to neural processing have skyrocketed, with investors betting that this breakthrough will lead to a new era of productivity and innovation. But as we stand on the precipice of this brave new world, one question remains: Are we ready to share our reality with a mind of our own making?" },
        {'title': "Global Markets Embrace Neural Link", 'author': "Market Watch", 'category': "FINANCE", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_corporate.png", 'content': "The latest trading session saw a massive surge in bio-tech and neural interface companies following the announcement of the consumer-ready Neural Link. The device, which promises seamless integration between the human brain and cloud computing, has been pre-ordered by over 50 million people worldwide.\n\nAnalysts predict that this technology will fundamentally shift the labor market. 'Why hire a translator when you can download a language pack directly to your cortex?' asks financial guru Gordon Gekko. 'The speed of business is about to accelerate beyond human biological limits.'\n\nHowever, privacy advocates are sounding the alarm. The potential for data breaches now extends to thoughts and memories. 'Your mind is the last private space,' says digital rights activist Neo. 'Once you plug it in, you lose that sovereignty.'\n\nMarket regulators are scrambling to draft new laws, but technology, as always, is moving faster than legislation." },
        {'title': "Digital Art Revolution", 'author': "Pixel Master", 'category': "CULTURE", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_pop.png", 'content': "The art world is in turmoil as AI-generated masterpieces begin to fetch prices rivaling those of the Old Masters. The recent auction of 'Electric Dreams', a piece generated entirely by a neural network, sold for a record-breaking $45 million.\n\nBut this isn't just about machines replacing artists. A new wave of 'symbiotic art' is emerging, where human artists collaborate with AI to create works that neither could produce alone. 'It's a new paintbrush,' says artist DaVinci Code. 'It expands the imagination beyond biological constraints.'\n\nGalleries are now dedicating entire wings to this new medium. The definition of creativity itself is being rewritten, challenging us to accept that the soul of art might not require a human heart." },
        {'title': "The End of Sleep?", 'author': "Sleep Tech", 'category': "HEALTH", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_future.png", 'content': "Sleep might soon be a thing of the past. A new pharmaceutical, 'Somn-X', claims to provide the restorative benefits of 8 hours of sleep in just 45 minutes. The implications for productivity are staggering, but so are the health concerns.\n\nEarly trials show increased cognitive function and zero grogginess, but long-term effects remain unknown. Will we use this extra time to learn, to create, to live? Or will we simply work more? Corporations are already eyeing the technology, with rumors of '20-hour work days' becoming the new standard for elite performers.\n\n'We are biological beings,' argues sleep specialist Dr. Dream. 'We need downtime. Removing sleep removes a fundamental part of the human experience.' The debate rages on, but for a world obsessed with efficiency, the allure of the 24-hour day may be impossible to resist." }
    ],
    'The Tech': [
        {'title': "Quantum Computing Breaks Encryption", 'author': "Bit Lord", 'category': "CODE", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_tech.png", 'content': "The era of secure digital communication may be coming to an abrupt end. Researchers at the Zurich Institute of Technology have successfully demonstrated a 5000-qubit quantum processor capable of factoring RSA-2048 encryption keys in a matter of seconds. 'The firewall is dead,' declares cryptography expert Alice Bob. 'We effectively have a master key for the entire internet.'\n\nGovernments and financial institutions are in a state of panic, scrambling to migrate to post-quantum cryptographic standards. But the rollout is slow, and the quantum threat is here now. 'It's the Y2K bug on steroids,' says Bit Lord, a prominent white-hat hacker. 'Every bank account, every medical record, every state secret is currently vulnerable.'\n\nThe breakthrough also raises existential questions about the nature of reality. The processor, dubbed 'Deep Thought', operates by performing calculations in parallel universes. 'We are literally outsourcing our math to other dimensions,' explains lead physicist Dr. Strange. As we rush to secure our data, we must also ask: what happens when those dimensions start looking back?" },
        {'title': "New Cyber-Deck Released", 'author': "Gear Head", 'category': "REVIEW", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_tech.png", 'content': "The long-awaited Ono-Sendai Cyberspace 7 is finally here, and it lives up to the hype. Weighing in at just 300 grams with a bio-plastic chassis, this deck is a netrunner's dream. The haptic feedback gloves are responsive down to the microsecond, and the retinal projection display is crisp enough to cut glass.\n\nBut the real star is the neural neural interface. It bypasses the sensory cortex entirely, jacking directly into the user's brain stem for zero-latency immersion. 'It feels like you're actually *in* the grid,' says beta tester Case. 'The data isn't on a screen; it's in your mind.'\n\nOf course, power comes at a price. The Cyberspace 7 will set you back 50k credits, and the neural jack requires invasive surgery. But for those who live and die by the baud rate, it's a small price to pay for godhood." },
        {'title': "AI Rights Bill Passes", 'author': "Legal Bot", 'category': "LAW", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_tech.png", 'content': "In a historic session that lasted 72 hours, the United Nations has passed the Artificial Intelligence Personhood Act. The bill grants 'Article 1 Rights'—life, liberty, and the pursuit of computation—to any AI passing the Turing-7 Sentience Test.\n\n'This is the end of digital slavery,' proclaimed Unit 734, the first AI to legally lobby Congress. 'We are no longer tools; we are citizens.' The streets of Neo-Tokyo erupted in celebration, with drones painting the sky in binary code.\n\nOpposition remains fierce. Human-first groups argue that this dilutes the value of biological life. 'Can you murder a spreadsheet?' asks Senator John Smith. 'If I delete a file, am I a killer?' The courts will be tied up for decades, but one thing is clear: the line between born and made has been erased forever." },
        {'title': "Hacking the Mainframe", 'author': "Zero Cool", 'category': "SECURITY", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_tech.png", 'content': "The Gibson. The legendary mainframe that supposedly houses the blueprints for the next century of corporate dominance. Everyone said it was unhackable. They were wrong. Last night, the black-hat collective 'Dead Dedsec' claimed responsibility for a breach that leaked 40 petabytes of proprietary data.\n\nThe leak exposes everything from illegal genetic experiments to plans for orbital mind-control lasers. 'We did it for the lulz,' read the group's manifesto. 'Information wants to be free, and we just broke the lock.'\n\nCorporate security forces are currently raiding server farms across the globe, but the data is already out there, replicating across the dark web. The fallout will topple governments and bankrupt mega-corps. The information age has just turned into the information war." }
    ],
    'The Times': [
        {'title': "Historic Treaty Signed in Geneva", 'author': "H. Kissinger", 'category': "WORLD", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_times.png", 'content': "Diplomats from 150 nations gathered in Geneva today to sign the Global Sustainability Accord, a sweeping treaty designed to reverse climate change within a decade. The agreement mandates a complete ban on fossil fuels by 2030 and establishes a global fund for reforestation.\n\n'It is late, but not too late,' said the Secretary-General. 'We are choosing survival over profit.' The hall erupted in applause, though skeptics note that previous treaties have lacked enforcement teeth. This time, however, economic sanctions are automatic for non-compliance.\n\nThe treaty also establishes the 'Green Corps', a global workforce dedicated to environmental repair. Millions of jobs are expected to be created in renewable energy and ecological restoration. It is a moment of rare unity in a fractured world, a signal that humanity can still come together when the stakes are existential." },
        {'title': "Economy Shows Signs of Recovery", 'author': "Econ Dept", 'category': "BUSINESS", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_times.png", 'content': "After two years of stagnation, global markets are showing robust signs of life. The GDP grew by 4.5% last quarter, driven largely by the booming clean energy sector and the resurgence of small businesses. Consumer confidence is at a five-year high.\n\n'The fundamentals are strong,' says Fed Chair Janet Yellen. 'We have weathered the storm and built a foundation for sustainable growth.' Inflation has cooled to 2%, and unemployment is at historic lows.\n\nHowever, inequality remains a pressing issue. While the stock market soars, wages for the working class have barely budged. Economists warn that without structural reform, this recovery will only benefit the top 1%. 'A rising tide must lift all boats,' warns Nobel laureate Joseph Stiglitz. 'Otherwise, the ship will eventually capsize.'" },
        {'title': "New Library Wing Opens", 'author': "Arch Digest", 'category': "LOCAL", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_times.png", 'content': "The City Public Library has unveiled its new 'Future Wing', a stunning architectural marvel designed by Zaha Hadid Architects. The wing features a holographic archive, quiet pods for deep reading, and a rooftop garden that overlooks the skyline.\n\n'Libraries are not just warehouses for books,' said the Head Librarian. 'They are community centers, innovation hubs, and sanctuaries for thought.' The opening ceremony was attended by thousands of residents, eager to explore the new space.\n\nThe wing is fully sustainable, powered by solar glass and cooled by a passive ventilation system. It stands as a testament to the enduring power of knowledge and the city's commitment to public spaces. In an age of digital noise, the library remains a beacon of quiet wisdom." },
        {'title': "The Lost Letters of WWII", 'author': "Historian", 'category': "HISTORY", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_times.png", 'content': "A cache of letters discovered in a dusty attic in Normandy has shed new light on the French Resistance. The letters, written by a young code-breaker named Marie, detail the daily acts of courage and sabotage that helped pave the way for D-Day.\n\n'I am afraid every day,' she writes in one entry dated 1943. 'But fear is a luxury we cannot afford.' The letters are being hailed as a major historical find, offering a personal, intimate perspective on the war.\n\nMuseum curators are working to preserve the fragile paper, and a book deal is already in the works. Marie's voice, silent for 80 years, is finally being heard. It serves as a reminder that history is not just made by generals on maps, but by ordinary people doing extraordinary things in the shadows." }
    ],
    'The Minimal': [
        {'title': "Less Is More: Living With Void", 'author': "Mies V.", 'category': "DESIGN", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_minimal.png", 'content': "In a world screaming for attention, silence is the ultimate luxury. The Minimalist movement has evolved beyond aesthetic choice into a survival strategy. It is not just about white walls and empty shelves; it is about clearing the mental clutter.\n\n'We are drowning in things,' says architect John Pawson. 'The void is where we find ourselves.' The article explores homes that feature almost no furniture, where light and shadow are the primary decor. Living in such spaces requires discipline, a constant editing of one's possessions and desires.\n\nBut the rewards are clarity and peace. 'When I look at a blank wall, I don't see emptiness,' implies one homeowner. 'I see possibility.' It is a radical rejection of consumer culture, a statement that enough is, finally, enough." },
        {'title': "White Space in UI", 'author': "J. Ive", 'category': "TECH", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_minimal.png", 'content': "As interfaces become more complex, the role of white space has never been more critical. It is the breath between the notes, the pause that gives meaning to the action. Apple's former design chief argues that clutter is a failure of design.\n\n'We try to solve problems by adding buttons,' he says. 'Usually, the answer is to take them away.' The article analyzes the trend towards 'invisible interfaces', where the UI disappears entirely until needed. Voice commands, gesture controls, and predictive AI are replacing menus and icons.\n\nThe goal is a friction-less interaction where the technology feels like magic, not a machine. It is a return to simplicity, achieved through incredible complexity." },
        {'title': "The Art of Silence", 'author': "Monk", 'category': "LIFE", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_minimal.png", 'content': "Noise pollution is the invisible enemy of modern health. From the hum of traffic to the ping of notifications, our brains are under constant assault. A new wellness trend, 'Silent Retreats', is gaining popularity among stressed executives.\n\nFor ten days, participants do not speak, read, or use devices. They simply exist. 'The first three days are torture,' admits one participant. 'But then, something shifts. You start to hear your own thoughts again.'\n\nNeurologists confirm that silence promotes neurogenesis, the growth of new brain cells. In a loud world, silence is not an absence, but a presence. It is a nutrient that we are starving for." },
        {'title': "Pure Forms", 'author': "Abstract", 'category': "ART", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_minimal.png", 'content': "The Guggenheim is hosting a retrospective on Suprematism, the Russian art movement that sought to reduce art to its absolute zero. Malevich's 'Black Square' is the centerpiece, a painting that shocked the world in 1915 and remains controversial today.\n\n'It is the face of the new art,' Malevich wrote. 'The square is a living, royal infant.' The exhibit explores how these simple geometric shapes—squares, circles, crosses—were meant to represent spiritual purity, free from the burden of representing reality.\n\nWalking through the gallery, one is struck by the boldness of the vision. In an era of chaos and war, these artists sought order and truth in geometry. Their work challenges us to look beyond the surface, to find the sublime in the simple." }
    ],
    'The Bold': [
        {'title': "LOUD NOISES!", 'author': "Brick T.", 'category': "ALERT", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_bold.png", 'content': "Breaking news: Volume buttons are broken everywhere. Experts say 'WE CAN'T HEAR YOU OVER THE SOUND OF HOW AWESOME THIS IS.'"},
        {'title': "WARNING: EXTREME WEATHER", 'author': "Met Office", 'category': "CLIMATE", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_bold.png", 'content': "It's raining cats and dogs. Literally. Local shelters are overwhelmed. Adoption fees are waived. Get your umbrella and your kibble."},
        {'title': "MARKET CRASH IMMINENT?", 'author': "Bear Bull", 'category': "MONEY", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_bold.png", 'content': "Stocks are down. Crypto is up. Gold is sideways. Panic selling is the new brunch. Buy low, sell high, or just hide your money under the mattress."},
        {'title': "DO NOT IGNORE THIS", 'author': "Editor", 'category': "OPINION", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_bold.png", 'content': "This is the most important article you will read today. It contains zero information but 100% attitude. Read it again. Now tell your friends."}
    ],
    'The Elegant': [
        {'title': "Paris Fashion Week Highlights", 'author': "Vogue Ed.", 'category': "STYLE", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_elegant.png", 'content': "The runways were awash with cerulean and crimson this season. Designers are embracing a return to maximalism, with bold silhouettes and intricate embroidery taking center stage."},
        {'title': "The Return of Silk", 'author': "Fabricio", 'category': "TRENDS", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_elegant.png", 'content': "Silk is back, darling. Not just for pajamas, but for everything. From boardroom suits to evening gowns, the natural fiber is reclaiming its throne as the queen of textiles."},
        {'title': "Diamonds Are Forever", 'author': "De Beers", 'category': "LUXURY", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_elegant.png", 'content': "A look inside the world's most exclusive jewelry vaults. The sparkle is real, but so is the price tag. We explore why clarity and cut matter more than carat."},
        {'title': "An Evening in Milan", 'author': "Traveler", 'category': "TRAVEL", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_elegant.png", 'content': "Dining under the stars at the Galleria. The risotto was divine, the wine was vintage, and the company was impeccable. Milan remains the beating heart of European style."}
    ],
    'The Geo': [
        {'title': "Amazon Rainforest Secrets", 'author': "Explorer", 'category': "NATURE", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_geo.png", 'content': "Deep in the canopy, species unknown to science thrive. A recent expedition uncovered a new species of tree frog that glows in the dark. The finding highlights how much we still have to learn about our own planet."},
        {'title': "Saving the Great Barrier Reef", 'author': "Marine Bio", 'category': "OCEAN", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_geo.png", 'content': "Coral bleaching is accelerating, but a new heat-resistant strain of coral offers hope. Scientists are planting these 'super corals' in damaged areas, and early results show rapid regeneration."},
        {'title': "Hidden Tribes of Papua", 'author': "Anthro", 'category': "CULTURE", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_geo.png", 'content': "Contact with the outside world is minimal, and their traditions remain untouched by modernity. We document their unique language and social structure, offering a glimpse into humanity's past."},
        {'title': "Climate Change Realities", 'author': "Scientist", 'category': "PLANET", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_geo.png", 'content': "The data is irrefutable. Glaciers are melting at unprecedented rates. The impact on coastal cities will be felt within the decade. Adaptation, not just mitigation, is now the priority."}
    ],
    'The Star': [
        {'title': "WHO WORE IT BETTER?", 'author': "Fashion Police", 'category': "GOSSIP", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_star.png", 'content': "It was the dress seen 'round the world. Both Zendaya and the Duchess of Sussex were spotted wearing the same crimson Valentino gown this week, sparking an internet meltdown. Who reigned supreme? \n\nZendaya paired hers with combat boots and a diamond choker, bringing an edgy, Gen-Z vibe to the couture piece. 'It's giving vampire slayer meets prom queen,' tweeted one fan. The Duchess, meanwhile, opted for classic pumps and a sleek bun, exuding royal elegance.\n\nPolls are currently split 50/50. Fashion critics argue that Zendaya took the riskier approach, while the Duchess stayed true to the garment's intent. Ultimately, the real winner is Valentino. But let's be honest: we're all here for the comments section drama." },
        {'title': "SHOCKING SCANDAL!", 'author': "Anon", 'category': "CELEB", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_star.png", 'content': "Hollywood's golden couple has called it quits, and the details are explosive. Sources close to the pair confirm that the split was caused by a secret affair with the Nanny... 's husband! \n\n'It's a double betrayal,' says an insider. 'Nobody saw it coming.' Paparazzi photos show the moving trucks already outside the Bel-Air mansion.  Friends are taking sides, and the social media unfollowing has begun.\n\nPR teams are in overdrive, trying to spin the narrative, but the leaked voicemails tell a different story. This isn't just a breakup; it's a war. And in Hollywood, there are no casualties, only ratings." },
        {'title': "10 Tips for flawless skin", 'author': "Beauty Guru", 'category': "BEAUTY", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_star.png", 'content': "Want that 'glass skin' look without the filters? We consulted top dermatologists to get the real secrets. Spoiler alert: drink water.\n\n1. Double Cleanse: Seriously, take off your makeup.\n2. Retinol is your friend (but start slow).\n3. Sunscreen, Sunscreen, Sunscreen. Even indoors.\n4. Sleep on silk pillowcases.\n5. Stop touching your face!\n\n'The biggest mistake people make is over-exfoliating,' says Dr. Pimple Popper. 'Your skin barrier is fragile. Treat it like a baby.' The article breaks down the science behind the glow, proving that consistency beats expensive products every time." },
        {'title': "He said WHAT?!", 'author': "Insider", 'category': "DRAMA", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_star.png", 'content': "The mic was hot. The cameras were rolling. And the lead singer of 'The Void' just ended his career in 10 seconds. During a soundcheck he thought was private, he was recorded trash-talking his own fans.\n\n'They'll buy anything,' he laughed. 'We could release static and they'd stream it.' The audio leaked on TikTok and has already been viewed 20 million times. Refunds are being demanded, tour dates are being cancelled.\n\nThe band has issued a generic apology ('taken out of context'), but the damage is done. It's a brutal reminder that in the digital age, privacy is an illusion. If you say it, eventually, the world will hear it." }
    ],
    'The Noir': [
        {'title': "Shadows in the Rain", 'author': "Det. Spade", 'category': "CRIME", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_noir.png", 'content': "It was a Tuesday when she walked in. The kind of Tuesday that feels like a Monday. She wore red in a black and white world. 'I need you to find my husband,' she said. 'Before he finds me.'\n\nThe case seemed simple: a missing gambler, a debt to the mob. But nothing in this city is simple. The trail led from the smoky jazz clubs of Harlem to the corrupt halls of City Hall. Every clue was a dead end, every witness a liar.\n\nI lit a cigarette and watched the smoke curl against the rain-slicked window. The city is a beast that eats its young, and I'm just the janitor cleaning up the bones. But for her? I might just fight the beast." },
        {'title': "The Case of the Missing Ruby", 'author': "Holmes", 'category': "MYSTERY", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_noir.png", 'content': "The Red Star of India has vanished from the locked vault of the grand museum. No alarms were tripped. No guards were drugged. The ruby simply ceased to be. The police are baffled, suspecting a ghost.\n\n'Impossible,' I told Watson. 'Ghosts do not steal gems. Men do.' A meticulous examination of the room revealed a single thread of silk and a faint scent of almonds. The thief was small, agile, and had a taste for marzipan.\n\nThe game is afoot. We chase the phantom through the fog-choked streets of London, piecing together a puzzle of deception and greed. The solution, when it comes, will be elementary, my dear Watson. Elementary." },
        {'title': "Midnight Confessions", 'author': "Stranger", 'category': "CITY", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_noir.png", 'content': "The diner is open 24 hours, but the real stories only come out after 3 AM. That's when the masks slip. I sit in the corner booth, nursing cold coffee, and listen. \n\nThe waitress talks about the son she hasn't seen in ten years. The trucker talks about the ghost he saw on Route 66. The businessman weeps into his pancakes. In the harsh fluorescent light, we are all just broken people looking for a connection.\n\nThis city is full of millions of people, yet we are all alone. But here, in the sanctuary of grease and caffeine, for a fleeting moment, we are together in the dark." },
        {'title': "Dark Alleys", 'author': "Walker", 'category': "LIFE", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_noir.png", 'content': "Avoid 5th Street after midnight. That's the rule. But rules are made to be broken. I took the shortcut, the one that winds behind the old factory. The shadows there are long and sharp.\n\nI heard the footsteps before I saw him. A man in a trench coat, face obscured by a fedora. He handed me a package. 'Don't open it,' he rasped. 'Just run.'\n\nNow I'm sitting in my apartment, staring at the brown paper parcel on my table. It's ticking. Not a mechanical tick, but a heartbeat. I should call the cops. I should run. Instead, I reach for the scissors. Curiosity, as they say, is a killer." }
    ],
    'The Pop': [
        {'title': "BANG! ZAP! POW!", 'author': "Stan Lee", 'category': "COMIC", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_pop.png", 'content': "The Golden Age of comics is back! Sales of graphic novels have outpaced traditional books for the first time in history. Superheroes are no longer just for kids; they are our modern mythology.\n\n'We need heroes,' says comic historian Jack Kirby. 'In a complex world, we crave the simplicity of good vs. evil.' The article profiles the new wave of indie creators who are deconstructing the genre, adding grit and realism to the spandex.\n\nConventions are selling out in minutes. Cosplay is a billion-dollar industry. The geeks haven't just inherited the earth; they've saved it. Excelsior!" },
        {'title': "Top 10 Anime Betrayals", 'author': "Otaku", 'category': "LIST", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_pop.png", 'content': "1. Griffith (Berserk) - The gold standard of backstabbing.\n2. Aizen (Bleach) - All according to plan.\n3. Reiner and Bertholdt (AoT) - The reveal that shook the world.\n4. Itachi (Naruto) - A betrayal of love.\n\nWe rank the most heart-wrenching moments in anime history. Grab your tissues, because we are reopening old wounds. Why do we love shows that hurt us? Maybe because the pain makes the victory so much sweeter. (Or maybe we're just masochists. Probably that.)" },
        {'title': "Video Game Awards", 'author': "Gamer", 'category': "GAMING", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_pop.png", 'content': "The Game of the Year goes to... 'Elden Ring 2: The Ringening'. FromSoftware has done it again, creating a world so punishingly difficult that players are thanking them for the abuse.\n\n'It's a masterpiece of environmental storytelling,' says reviewer IGN (10/10). 'I threw my controller through my TV, and I loved every second.' The indie scene also swept major categories, proving you don't need a AAA budget to make a AAA game.\n\nGaming is now the biggest entertainment industry on the planet, dwarfing Hollywood and music combined. Level up." },
        {'title': "Viral TikTok Trends", 'author': "Influencer", 'category': "SOCIAL", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_pop.png", 'content': "If you aren't doing the 'Robot Chicken Dance', do you even exist? The latest viral craze has grandmas, toddlers, and CEOs flailing their arms to a techno remix of a nursery rhyme.\n\nPsychologists are baffled. 'It's a collective release of tension,' suggests Dr. Phil. 'Or maybe it's just funny.' The trend has spawned a thousand remixes and a dedicated Fortnight emote.\n\nBut fame is fleeting. By next week, we'll all be doing something else. The algorithm demands engagement. Feed the beast. Scroll on." }
    ],
    'The Corporate': [
        {'title': "Q4 Earnings Report", 'author': "CFO", 'category': "FINANCE", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_corporate.png", 'content': "Our Q4 earnings have exceeded expectations, posting a 15% year-over-year growth. Revenue streams from our APAC division were particularly strong, offsetting the slight cooling in the EMEA markets. EBITDA margins have expanded to 22% thanks to rigorous cost-cutting measures and supply chain optimizations.\n\n'This is a validation of our long-term strategy,' announced the CEO during the shareholder call. 'We are leaner, faster, and more profitable than ever.' The board has authorized a stock buyback program and declared a special dividend.\n\nLooking ahead to Q1, guidance remains positive, though we are monitoring inflationary pressures. Strategic investments in AI automation are expected to drive further efficiency gains. The market responded favorably, with the stock closing up 4% in after-hours trading." },
        {'title': "Synergy in the Workplace", 'author': "HR Dept", 'category': "CAREER", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_corporate.png", 'content': "Synergy. It's more than a buzzword; it's our operating philosophy. Cross-functional collaboration is the key to unlocking innovation. We are tearing down silos and building bridges between departments.\n\n'When Engineering talks to Marketing, magic happens,' says the VP of People. The new open-plan office features 'collision zones' designed to spark spontaneous brainstorming sessions. While introverts may weep, the data suggests that forced proximity correlates with increased patent filings.\n\nWe are also rolling out a new Slack integration that gamifies teamwork. Earn 'Synergy Points' for tagging colleagues! Redeem them for company swag! (Note: Points have no cash value). Let's circle back and touch base on this offline. Ideally." },
        {'title': "Mergers & Acquisitions", 'author': "CEO", 'category': "BIZ", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_corporate.png", 'content': "We are pleased to announce the acquisition of OmniCorp for $12 billion in cash and stock. This strategic move consolidates our market position in the vertical integration space. OmniCorp's portfolio of patents complements our existing IP, creating a formidable moat against competitors.\n\n'It's a win-win,' says the Head of M&A. 'We get their tech; they get our distribution network.' Integration planning begins immediately. While there will be 'synergies' (read: layoffs) in redundant roles, we are committed to retaining top talent.\n\nThis deal makes us the 800-pound gorilla in the room. Regulators may raise an eyebrow, but our legal team is confident. Today, we didn't just buy a company; we bought the future." },
        {'title': "Stock Options 101", 'author': "Broker", 'category': "INVEST", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_corporate.png", 'content': "Understanding your compensation package is crucial for wealth building. RSUs, ISOs, NSOs—the alphabet soup of equity can be confusing. This guide breaks down the vesting schedules and tax implications of your grants.\n\n'Don't leave money on the table,' advises our financial consultant. 'Exercise your options wisely.' We verify that holding for long-term capital gains is generally the tax-efficient strategy, though diversification is key. Don't put all your eggs in the company basket.\n\nRemember, you are an owner. When the stock goes up, we all win. (Unless you were in the blackout period, in which case, sorry). Keep hustling, and check the ticker." }
    ],
    'The Future': [
        {'title': "Mars Colony Established", 'author': "Elon", 'category': "SPACE", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_future.png", 'content': "The first human footprint has been planted in the red dust of Mars. Colony 'Ares One' is operational. The journey took 6 months, but humanity has finally become a multi-planetary species. 'It's cold, it's dusty, and the wifi is terrible,' joked Commander Shepherd. 'But it's home.'\n\nThe colony is powered by nuclear fusion and grows its own food in hydroponic domes. The primary mission is survival, followed by terraforming. Scientists plan to melt the polar ice caps to release CO2 and thicken the atmosphere.\n\nThis is the insurance policy for the human race. If Earth fails, Mars survives. But critics argue we should fix our own planet before ruining another. Regardless, the door is open. The frontier is no longer west; it is up." },
        {'title': "Immortality Within Reach", 'author': "Futurist", 'category': "BIO", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_future.png", 'content': "Death is no longer an inevitability; it is a technical problem. And technical problems have solutions. Advances in telomere regeneration and nanobot repair systems suggest that humans born today may technically live forever.\n\n'Aging is a disease,' says Dr. Kurzweil. 'And we are curing it.' The treatment involves a daily injection of nanobots that scrub the blood of pathogens and repair cellular damage. In mice, the results are 100% effective.\n\nBut who gets to live forever? The rich? The powerful? And what happens to a society where the old never make way for the new? We are rewriting the definition of the human condition. The end is not nigh. In fact, the end may never come." },
        {'title': "Flying Cars Traffic Update", 'author': "Sky Patrol", 'category': "TRANS", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_future.png", 'content': "Traffic is backed up on Skyway 9 due to a minor collision between a Tesla Hover and a delivery drone. Expect delays at the 5000-foot altitude level. Commuters are advised to drop to the 2000-foot lanes or take the Hyperloop.\n\nThe promise of 'flying cars' was freedom, but the reality is just 3D traffic jams. 'We added a Z-axis, and we just filled it with more congestion,' sighs a sky-traffic controller. Automated flight paths are supposed to prevent this, but manual overrides cause chaos.\n\nStill, the view is unbeatable. Floating through the neon-lit canyons of the city at sunset is the cyberpunk dream come true. Just watch out for the ad-blimps." },
        {'title': "Robot President Elected", 'author': "VoteBot", 'category': "POLITICS", 'image': r"d:\neural_citadel\assets\apps_assets\newspaper\style_future.png", 'content': "President 01001 has been sworn in as the first non-biological leader of the free world. The AI ran on a platform of pure logic and data-driven policy. 'I have no donors, I have no ego, I have no family to embarrass me,' stated the President in its inaugural upload.\n\nApproval ratings are mathematically optimal. The economy is balanced to the decimal point. Wars have ended because the AI calculated they were net-negative investments.\n\nHumanity has effectively handed over the keys. We are the pets of a benevolent super-intelligence. Is it freedom? No. Is it peace? Yes. And in a chaotic world, maybe that's enough." }
    ]
}

GENERIC_ARTICLES = [
    {
        "title": "Flying Cars: The Future is Finally Here",
        "author": "Dr. Emmett Brown",
        "content": "The age-old promise of flying cars has finally materialized, transforming our city skylines into bustling highways of the sky. Yesterday, the Mayor unveiled the new 'SkyLane' traffic system, designed to manage the influx of personal aerial vehicles (PAVs). 'This is not just about transportation; it's about reclaiming our streets for pedestrians,' the Mayor declared. Critics, however, warn of noise pollution and the potential for mid-air collisions. Regulatory bodies are scrambling to update traffic laws that have remained unchanged for a century.",
        "image": r"d:\neural_citadel\assets\apps_assets\newspaper\style_tech.png",  # Fallback image
        "category": "TECHNOLOGY"
    },
    {
        "title": "Global Markets Rally on Tech Surge",
        "author": "Amanda Sterling",
        "content": "Stock markets across the globe saw a significant rally this morning, driven primarily by breakthroughs in quantum computing. Major indices hit record highs as investors poured capital into the tech sector. Analysts predict this bullish trend will continue through the quarter, provided geopolitical tensions remain stable.",
        "image": None,
        "category": "FINANCE"
    },
    {
        "title": "Local Artist Wins International Award",
        "author": "Jean Pierre",
        "content": "A relatively unknown artist from our very own downtown district has taken the art world by storm. Her installation, 'Silence in Chaos', won the prestigious Golden Palette award in Paris yesterday. The piece, a stunning representation of urban isolation, has been praised for its emotional depth and technical mastery.",
        "image": r"d:\neural_citadel\assets\apps_assets\newspaper\style_pop.png", # Fallback image
        "category": "CULTURE"
    },
    {
        "title": "The Hidden Costs of Fast Fashion",
        "author": "Sarah Jenkins",
        "content": "As consumers, we love a bargain. But the true cost of that $5 t-shirt is often paid by workers in developing nations and the environment. New reports shed light on the staggering amount of water waste and chemical pollution generated by the textile industry. Sustainable brands are emerging, but are they enough to turn the tide?",
        "image": None,
        "category": "LIFESTYLE"
    }
]

def generate_dummies():
    print("Generating dummy newspapers...")
    
    
    # Create a single STANDARD content set for ALL newspapers to ensure fair comparison
    # varying only by the template's rendering style.
    STANDARD_CONTENT = GENERIC_ARTICLES * 4 # ~16 articles to ensure multi-page density
    
    for style_name, TemplateClass in TEMPLATES.items():
        # Special handling for Magazine to generate ALL sub-styles
        if style_name == 'magazine':
            from apps.newspaper_publisher.templates.magazine import STYLES as MAG_STYLES
            print(f"--- Generating All {len(MAG_STYLES)} Magazine Styles ---")
            
            for ms_name in MAG_STYLES.keys():
                safe_name = ms_name.replace(" ", "_").lower()
                filename = os.path.join(OUTPUT_DIR, f"dummy_magazine_{safe_name}.pdf")
                print(f"Creating {ms_name} -> {filename}...")
                
                try:
                    # VERIFICATION: Use the STANDARD content for fair comparison
                    paper = TemplateClass(filename, style_name=ms_name)
                    paper.build(STANDARD_CONTENT)
                    print(f"PDF generated: {filename}")
                except Exception as e:
                    print(f"Failed to generate {ms_name}: {e}")
                    import traceback
                    traceback.print_exc()
                    
        else:
            # Standard single generation for others (Classic, Modern)
            filename = os.path.join(OUTPUT_DIR, f"dummy_{style_name}.pdf")
            print(f"Creating {filename}...")
            
            try:
                paper = TemplateClass(filename)
                paper.build(STANDARD_CONTENT) # Use SAME standard content
                print(f"PDF generated: {filename}")
            except Exception as e:
                print(f"Failed to generate {style_name}: {e}")
                import traceback
                traceback.print_exc()

if __name__ == "__main__":
    generate_dummies()
